import type { WorkflowData } from './components/WorkflowCard';

export const mockWorkflows: WorkflowData[] = [
  // All yellow
  {
    id: '1',
    name: 'Hans Herman',
    email: 'hans.herman@example.com',
    department: 'IT',
    location: 'Berlin',
    teamlead: 'Lisa Schmidt',
    exitDate: '2025-09-20',
    picture: 'https://mui.com/static/images/avatar/1.jpg',
    statuses: [
      { label: 'HR', completion: '1/3' },
      { label: 'IT', completion: '0/2' },
      { label: 'Finance', completion: '2/2' },
      { label: 'Team', completion: '2/4' },
    ],
    subflows: [],
  },
  // All red
  {
    id: '2',
    name: 'Lisa Schmidt',
    email: 'lisa.schmidt@example.com',
    department: 'HR',
    location: 'Munich',
    teamlead: 'John Miller',
    exitDate: '2025-09-25',
    picture: 'https://mui.com/static/images/avatar/2.jpg',
    statuses: [
      { label: 'HR', completion: '0/1' },
      { label: 'IT', completion: '1/2' },
      { label: 'Finance', completion: '1/1' },
      { label: 'Team', completion: '1/1' },
    ],
    subflows: [],
  },
  // All red
  {
    id: '3',
    name: 'Markus Braun',
    email: 'markus.braun@example.com',
    department: 'Finance',
    location: 'Berlin',
    teamlead: 'Emily Clark',
    exitDate: '2025-10-01',
    picture: 'https://mui.com/static/images/avatar/3.jpg',
    statuses: [
      { label: 'HR', completion: '2/2' },
      { label: 'IT', completion: '1/3' },
      { label: 'Finance', completion: '0/2' },
      { label: 'Team', completion: '2/4' },
    ],
    subflows: [],
  },
  // Mixed
  {
    id: '4',
    name: 'Julia Meier',
    email: 'julia.meier@example.com',
    department: 'IT',
    location: 'Hamburg',
    teamlead: 'Lisa Schmidt',
    exitDate: '2025-10-05',
    picture: 'https://mui.com/static/images/avatar/4.jpg',
    statuses: [
      { label: 'HR', completion: '1/2' },
      { label: 'IT', completion: '3/3' },
      { label: 'Finance', completion: '1/2' },
      { label: 'Team', completion: '0/2' },
    ],
    subflows: [],
  },
  // Mixed
  {
    id: '5',
    name: 'Peter Müller',
    email: 'peter.mueller@example.com',
    department: 'HR',
    location: 'Berlin',
    teamlead: 'John Miller',
    exitDate: '2025-10-10',
    picture: 'https://mui.com/static/images/avatar/5.jpg',
    statuses: [
      { label: 'HR', completion: '2/2' },
      { label: 'IT', completion: '2/4' },
      { label: 'Finance', completion: '0/1' },
      { label: 'Team', completion: '1/2' },
    ],
    subflows: [],
  },
  // Mixed
  {
    id: '6',
    name: 'Anna Fischer',
    email: 'anna.fischer@example.com',
    department: 'Finance',
    location: 'Munich',
    teamlead: 'Emily Clark',
    exitDate: '2025-10-15',
    picture: 'https://mui.com/static/images/avatar/6.jpg',
    statuses: [
      { label: 'HR', completion: '0/2' },
      { label: 'IT', completion: '2/2' },
      { label: 'Finance', completion: '1/3' },
      { label: 'Team', completion: '2/2' },
    ],
    subflows: [],
  },
  // Mixed
  {
    id: '7',
    name: 'Tom Becker',
    email: 'tom.becker@example.com',
    department: 'IT',
    location: 'Hamburg',
    teamlead: 'Lisa Schmidt',
    exitDate: '2025-10-20',
    picture: 'https://mui.com/static/images/avatar/7.jpg',
    statuses: [
      { label: 'HR', completion: '1/2' },
      { label: 'IT', completion: '2/3' },
      { label: 'Finance', completion: '2/2' },
      { label: 'Team', completion: '0/1' },
    ],
    subflows: [],
  },
  // Mixed
  {
    id: '8',
    name: 'Sophie Klein',
    email: 'sophie.klein@example.com',
    department: 'Finance',
    location: 'Berlin',
    teamlead: 'John Miller',
    exitDate: '2025-10-25',
    picture: 'https://mui.com/static/images/avatar/8.jpg',
    statuses: [
      { label: 'HR', completion: '2/2' },
      { label: 'IT', completion: '0/2' },
      { label: 'Finance', completion: '1/2' },
      { label: 'Team', completion: '1/3' },
    ],
    subflows: [],
  },
  // Mixed
  {
    id: '9',
    name: 'Max Weber',
    email: 'max.weber@example.com',
    department: 'HR',
    location: 'Munich',
    teamlead: 'Emily Clark',
    exitDate: '2025-10-30',
    picture: 'https://mui.com/static/images/avatar/9.jpg',
    statuses: [
      { label: 'HR', completion: '1/2' },
      { label: 'IT', completion: '2/2' },
      { label: 'Finance', completion: '0/1' },
      { label: 'Team', completion: '2/2' },
    ],
    subflows: [],
  },
  // Mixed
  {
    id: '10',
    name: 'Clara Wolf',
    email: 'clara.wolf@example.com',
    department: 'IT',
    location: 'Berlin',
    teamlead: 'Lisa Schmidt',
    exitDate: '2025-11-05',
    picture: 'https://mui.com/static/images/avatar/10.jpg',
    statuses: [
      { label: 'HR', completion: '2/2' },
      { label: 'IT', completion: '1/3' },
      { label: 'Finance', completion: '1/2' },
      { label: 'Team', completion: '0/2' },
    ],
    subflows: [],
  },
  // Mixed
  {
    id: '11',
    name: 'Felix König',
    email: 'felix.koenig@example.com',
    department: 'Finance',
    location: 'Hamburg',
    teamlead: 'John Miller',
    exitDate: '2025-11-10',
    picture: 'https://mui.com/static/images/avatar/11.jpg',
    statuses: [
      { label: 'HR', completion: '1/2' },
      { label: 'IT', completion: '2/2' },
      { label: 'Finance', completion: '0/1' },
      { label: 'Team', completion: '1/2' },
    ],
    subflows: [],
  },
];
